number:
  - unique_id: soundsend_volume
    device: !include inc/soundsend_device.yaml
    name: SoundSend volume
    state_topic: "wisa2mqtt/status/volume"
    command_topic: "wisa2mqtt/command/setvolume"
    availability: !include inc/soundsend_availability.yaml
    mode: slider
    min: 0
    max: 100
    unit_of_measurement: "%"
    icon: "mdi:volume-high"
    
  - unique_id: soundsend_eq_high
    device: !include inc/soundsend_device.yaml
    name: SoundSend EQ High
    state_topic: "wisa2mqtt/status/eq_high"
    command_topic: "wisa2mqtt/command/setEqHigh"
    availability: !include inc/soundsend_availability.yaml
    mode: slider
    min: -6
    max: 6
    icon: "mdi:equalizer"

  - unique_id: soundsend_eq_midrange
    device: !include inc/soundsend_device.yaml
    name: SoundSend EQ Mid-Range
    state_topic: "wisa2mqtt/status/eq_midrange"
    command_topic: "wisa2mqtt/command/setEqMidrange"
    availability: !include inc/soundsend_availability.yaml
    mode: slider
    min: -6
    max: 6
    icon: "mdi:equalizer"

  - unique_id: soundsend_eq_voice
    device: !include inc/soundsend_device.yaml
    name: SoundSend EQ Voice
    state_topic: "wisa2mqtt/status/eq_voice"
    command_topic: "wisa2mqtt/command/setEqVoice"
    availability: !include inc/soundsend_availability.yaml
    mode: slider
    min: -6
    max: 6
    icon: "mdi:equalizer"

  - unique_id: soundsend_eq_midbass
    device: !include inc/soundsend_device.yaml
    name: SoundSend EQ Mid-Bass
    state_topic: "wisa2mqtt/status/eq_midbass"
    command_topic: "wisa2mqtt/command/setEqMidbass"
    availability: !include inc/soundsend_availability.yaml
    mode: slider
    min: -6
    max: 6
    icon: "mdi:equalizer"

  - unique_id: soundsend_eq_subbass
    device: !include inc/soundsend_device.yaml
    name: SoundSend EQ Sub-Bass
    state_topic: "wisa2mqtt/status/eq_subbass"
    command_topic: "wisa2mqtt/command/setEqSubbass"
    availability: !include inc/soundsend_availability.yaml
    mode: slider
    min: -6
    max: 6
    icon: "mdi:equalizer"

select:
  - unique_id: soundsend_audio_mode
    device: !include inc/soundsend_device.yaml
    name: SoundSend mode
    state_topic: "wisa2mqtt/status/audiomode"
    command_topic: "wisa2mqtt/command/setaudiomode"
    availability: !include inc/soundsend_availability.yaml
    options:
      - direct
      - movie
      - music
      - night
    icon: "mdi:music"
  - unique_id: soundsend_audio_source
    device: !include inc/soundsend_device.yaml
    name: SoundSend source
    state_topic: "wisa2mqtt/status/audiosource"
    command_topic: "wisa2mqtt/command/setaudiosource"
    availability: !include inc/soundsend_availability.yaml
    options:
      - arc
      - optical
    icon: "mdi:connection"

sensor:
  - unique_id: soundsend_audio_format
    device: !include inc/soundsend_device.yaml
    name: SoundSend audio format
    state_topic: "wisa2mqtt/status/audioformat"
    availability: !include inc/soundsend_availability.yaml
    icon: "mdi:audio-input-stereo-minijack"

switch:
  - unique_id: soundsend_power
    name: SoundSend power
    state_topic: "wisa2mqtt/status/power"
    command_topic: "wisa2mqtt/command/setpower"
    payload_on: "true"
    payload_off: "false"
    availability: !include inc/soundsend_availability.yaml
    device: !include inc/soundsend_device.yaml
    icon: "mdi:power"
  - unique_id: soundsend_bassmanagement
    name: SoundSend bass management
    state_topic: "wisa2mqtt/status/bassmanagement"
    command_topic: "wisa2mqtt/command/setbassmanagement"
    payload_on: "true"
    payload_off: "false"
    availability: !include inc/soundsend_availability.yaml
    device: !include inc/soundsend_device.yaml
    icon: "mdi:volume-vibrate"
